#ifndef REMOTECOMPILER_GLOBAL_H
#define REMOTECOMPILER_GLOBAL_H

#include <QtGlobal>

#if defined(REMOTECOMPILER_LIBRARY)
#  define REMOTECOMPILERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define REMOTECOMPILERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // REMOTECOMPILER_GLOBAL_H

